version: '3.8'

services:
  web:
    image: php:8.2-apache   # The latest stable version of PHP 8.2
    container_name: php-web
    ports:
      - "8080:80"           # Expose port 80 (Apache) on port 8080
    volumes:
      - ./html:/var/www/html # Map local `html` directory to Apache's web root
    depends_on:
      - db                   # Wait for the `db` service to be ready
    networks:
      - app-network

  db:
    image: mysql:8.1         # The latest stable version of MySQL 8.1
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root   # Set root password for MySQL
      MYSQL_DATABASE: phplessen           # Create an initial database
      MYSQL_USER: phples                    # Create a non-root user
      MYSQL_PASSWORD: phples        # Set password for the non-root user
    ports:
      - "3306:3306"           # Expose MySQL port 3306
    volumes:
      - db_data:/var/lib/mysql # Persist MySQL data on local disk
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin:latest  # The latest stable version of phpMyAdmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: db            # Connect phpMyAdmin to the `db` service
      MYSQL_ROOT_PASSWORD: root # Provide root password for MySQL
    ports:
      - "8081:80"             # Expose phpMyAdmin on port 8081
    depends_on:
      - db                    # Wait for the `db` service to be ready
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
